import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GiHamburgerMenu } from "react-icons/gi";
import "./globals.css";
import { IconContext } from "react-icons";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex navbar rounded justify-between items-center px-10">
          <div>
            <a className="btn btn-ghost text-xl">Hello World</a>
          </div>
          <div>
            <button className="btn btn-square btn-ghost">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                className="inline-block w-5 h-5 stroke-current"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M4 6h16M4 12h16M4 18h16"
                ></path>
              </svg>
            </button>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
